### PR TITLE
Feature/change stream to be based on the camera u UI d

### PR DESCRIPTION
**Pull request by francis-guardi**
Change stream utl use the camera UUID.

### CODE REVIEW

**Comment by felmoreno1726** [comment]
Looks good to me!

**Comment by penghaolu** [comment]
lgtm too

**Review by penghaolu — APPROVED** [review]
lgtm

**Review by felmoreno1726 — APPROVED** [review]
Looks good! Sorry. I though I did the review, but I didn't "approve" it. Now done!

**Pull request closed without merging**
